### PR TITLE
feat: improve passkey sdk apis

### PR DESCRIPTION
**Pull request by mfmurray**
- Add passkey specific api's `rownd.Auth.Passkeys.register()` and `rownd.Auth.Passkeys.authenticate()`
- Replace userId with base64 encoded string for requestJson

### CODE REVIEW

**Comment by BobbyRadford** [comment]
I see that we already have a `Firebase` inner class that's called by `rownd.Firebase.getAccessToken()`, so `rownd.Auth.Passkeys.register()` follows the casing convention, but unless this is an Android thing, the capital letters throw me off.

**Comment by mfmurray** [comment]
> I see that we already have a `Firebase` inner class that's called by `rownd.Firebase.getAccessToken()`, so `rownd.Auth.Passkeys.register()` follows the casing convention, but unless this is an Android thing, the capital letters throw me off.

I do like sticking with across our SDK's. I made `Auth` and `Passkey` uppercase because of a Android Studio complaining classes are typically uppercase.

**Comment by BobbyRadford** [comment]
> > I see that we already have a `Firebase` inner class that's called by `rownd.Firebase.getAccessToken()`, so `rownd.Auth.Passkeys.register()` follows the casing convention, but unless this is an Android thing, the capital letters throw me off.
> 
> I do like sticking with convention across our SDK's. I made `Auth` and `Passkey` uppercase because of Android Studio complaining classes are typically uppercase.

Even if the class names are capitalized, we could still expose it through the `rownd` interface as lowercase. I'm not gonna be a huge stickler on this, but it just looks weird to me

**Comment by mfmurray** [comment]
> > > I see that we already have a `Firebase` inner class that's called by `rownd.Firebase.getAccessToken()`, so `rownd.Auth.Passkeys.register()` follows the casing convention, but unless this is an Android thing, the capital letters throw me off.
> > 
> > 
> > I do like sticking with convention across our SDK's. I made `Auth` and `Passkey` uppercase because of Android Studio complaining classes are typically uppercase.
> 
> Even if the class names are capitalized, we could still expose it through the `rownd` interface as lowercase. I'm not gonna be a huge stickler on this, but it just looks weird to me

I agree. It's been update to lowercase

**Review by mhamann — APPROVED** [review]

**Pull request merged**
